### ISSUE TITLE
lack of multi tag support

### ISSUE THREAD

**Issue by jafarrasooli** [jafarrasooli/timeSheet#10]
in 'getRecordsByDate' service , for each record we should have an array as the value of tag key. in the current version it just get a string

	    {
	        "records": [
	            {
	                "id": 1,
	                "task": "t1",
	                "sTime": "10:20:30",
	                "eTime": "12:13:14",
	                "index": "1",
	                "org": "org1",
	                "tag": "tag1"
	            },
	            {
	                "id": 2,
	                "task": "t2",
	                "sTime": "10:20:30",
	                "eTime": "12:13:14",
	                "index": "2",
	                "org": "org2",
	                "tag": "tag2"
	            }
	        ],
	        "status": "success"
	    }

should change to 

	    {
	        "records": [
	            {
	                "id": 1,
	                "task": "t1",
	                "sTime": "10:20:30",
	                "eTime": "12:13:14",
	                "index": "1",
	                "org": "org1",
	                "tag": ["tag1","tag2"]
	            },
	            {
	                "id": 2,
	                "task": "t2",
	                "sTime": "10:20:30",
	                "eTime": "12:13:14",
	                "index": "2",
	                "org": "org2",
	                "tag": ["tag1","tag2"]
	            }
	        ],
	        "status": "success"
	    }

**Comment by yaghouti** [comment]
Done. Please check documents for details.
